/**
 * CleanFrame — MV3 service worker.
 * Ensures offscreen document, relays process jobs, and sniffs HD media URLs.
 */
/* global CLEANFRAME_CONFIG */
importScripts('config.js');

const CFG = self.CLEANFRAME_CONFIG;
const MSG = CFG.messages;
const OFFSCREEN_URL = 'offscreen.html';

let creatingOffscreen = null;

/** @type {Map<number, { url: string, bytes?: number, ts: number }[]>} */
const mediaByTab = new Map();
const MEDIA_CACHE_LIMIT = 40;
const MEDIA_TTL_MS = 15 * 60 * 1000;

/**
 * Registry of in-flight phantom-click captures.
 * Key: requestId (UUID generated by the content script)
 * Value: { requestId, tabId, cardUuid, armedAt, timeoutMs }
 * @type {Map<string, { requestId: string, tabId: number, cardUuid: string|null, armedAt: number, timeoutMs: number }>}
 */
const pendingCaptures = new Map();
const DEFAULT_CAPTURE_TIMEOUT_MS = 8000;
const CAPTURE_GRACE_MS = 5000;
const UPSAMPLED_SUFFIX = '_upsampled';

function prunePendingCaptures() {
  const now = Date.now();
  for (const [id, entry] of pendingCaptures) {
    const ttl = (entry.timeoutMs || DEFAULT_CAPTURE_TIMEOUT_MS) + CAPTURE_GRACE_MS;
    if (now - entry.armedAt > ttl) pendingCaptures.delete(id);
  }
}

function isMediaUrl(url) {
  if (!url || typeof url !== 'string') return false;
  const patterns = CFG.mediaUrlPatterns || ['.mp4', 'googleusercontent.com'];
  const lower = url.toLowerCase();
  if (/(?:preview|thumb|thumbnail|sprite|waveform)/i.test(lower) && !/\.mp4/i.test(lower)) {
    return false;
  }
  return patterns.some((p) => lower.includes(p.toLowerCase()));
}

function rememberTabMedia(tabId, url, bytes) {
  if (tabId == null || tabId < 0 || !isMediaUrl(url)) return;
  const list = mediaByTab.get(tabId) || [];
  const existing = list.find((x) => x.url === url);
  if (existing) {
    existing.ts = Date.now();
    if (bytes) existing.bytes = bytes;
  } else {
    list.unshift({ url, bytes, ts: Date.now() });
  }
  while (list.length > MEDIA_CACHE_LIMIT) list.pop();
  mediaByTab.set(tabId, list);

  // Notify the content script so Strategy C stays warm
  chrome.tabs.sendMessage(tabId, {
    type: MSG.MEDIA_SEEN,
    url,
    bytes,
  }).catch(() => { });
}

function lookupMedia(tabId, hints = []) {
  const now = Date.now();
  const list = (mediaByTab.get(tabId) || []).filter((x) => now - x.ts < MEDIA_TTL_MS);
  mediaByTab.set(tabId, list);

  if (!hints.length) return list;

  const scored = list.map((item) => {
    let score = item.bytes ? Math.log10(item.bytes + 1) : 0;
    for (const h of hints) {
      if (h && item.url.includes(h)) score += 50;
    }
    if (/download|export|1080|2160|4k|original/i.test(item.url)) score += 20;
    if (/preview|proxy|thumb/i.test(item.url)) score -= 30;
    return { ...item, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored;
}

async function hasOffscreenDocument() {
  if (chrome.runtime.getContexts) {
    const contexts = await chrome.runtime.getContexts({
      contextTypes: ['OFFSCREEN_DOCUMENT'],
      documentUrls: [chrome.runtime.getURL(OFFSCREEN_URL)],
    });
    return contexts.length > 0;
  }
  return false;
}

async function ensureOffscreen() {
  if (await hasOffscreenDocument()) return;

  if (creatingOffscreen) {
    await creatingOffscreen;
    return;
  }

  creatingOffscreen = chrome.offscreen.createDocument({
    url: OFFSCREEN_URL,
    reasons: ['BLOBS', 'WORKERS', 'DOM_SCRAPING'],
    justification:
      'Run WebCodecs + WebGL2 watermark removal off the extension service worker.',
  });

  try {
    await creatingOffscreen;
  } finally {
    creatingOffscreen = null;
  }
}

async function relayToTab(tabId, message) {
  if (tabId == null) return;
  try {
    await chrome.tabs.sendMessage(tabId, message);
  } catch (err) {
    console.warn('[CleanFrame:background] tab relay failed', err);
  }
}

// ---------- Strategy C: chrome.webRequest HD sniffer ----------
if (chrome.webRequest?.onCompleted) {
  const filter = {
    urls: [
      '*://*.googleusercontent.com/*',
      '*://storage.googleapis.com/*',
      '*://*.googleapis.com/*',
      '*://labs.google.com/*',
      '*://labs.google/*',
      '*://*.ggpht.com/*',
      '*://*.flow-content.google/*',
      '*://flow-content.google/*',
    ],
    types: ['media', 'xmlhttprequest', 'other', 'object'],
  };

  chrome.webRequest.onCompleted.addListener(
    (details) => {
      if (details.tabId < 0) return;
      if (!isMediaUrl(details.url)) return;
      // Prefer larger responses — previews are often tiny
      const bytes = details.responseHeaders
        ? Number(
          details.responseHeaders.find(
            (h) => h.name.toLowerCase() === 'content-length'
          )?.value
        ) || undefined
        : undefined;
      console.log('[CleanFrame:background] webRequest media', details.url.slice(0, 120), bytes);
      rememberTabMedia(details.tabId, details.url, bytes);
    },
    filter,
    ['responseHeaders']
  );

  chrome.webRequest.onBeforeRequest.addListener(
    (details) => {
      if (details.tabId < 0) return;
      if (!isMediaUrl(details.url)) return;
      rememberTabMedia(details.tabId, details.url);
    },
    filter
  );
}

// ---------- Phantom-click redirect interceptor ----------
// Catches the 307 redirect from media.getMediaUrlRedirect → flow-content.google
// and delivers the signed Location URL back to the waiting content script.
if (chrome.webRequest?.onBeforeRedirect) {
  chrome.webRequest.onBeforeRedirect.addListener(
    (details) => {
      console.debug('[CleanFrame:background] onBeforeRedirect fired', details.url.slice(0, 120));
      if (details.tabId < 0) return;
      const redirectUrl = details.redirectUrl;
      if (!redirectUrl) return;

      // TODO: confirm the exact mediaUrlType value used for thumbnail exports
      // by inspecting a live manual export request in DevTools Network tab.
      // When confirmed, replace the string below with the actual value.
      const THUMBNAIL_TYPE = 'MEDIA_URL_TYPE_THUMBNAIL';
      if (details.url.includes(THUMBNAIL_TYPE)) {
        console.log('[CleanFrame:background] skipping thumbnail redirect', details.url.slice(0, 120));
        return;
      }

      console.log('[CleanFrame:background] phantom redirect caught', redirectUrl.slice(0, 120));

      // Accept both standard UUIDs and _upsampled UUIDs; strip suffix for correlation.
      let bareUuid = null;
      try {
        const urlObj = new URL(details.url);
        const nameParam = urlObj.searchParams.get('name');
        if (!nameParam) return; // Ignore if no name param

        bareUuid = nameParam.replace(UPSAMPLED_SUFFIX, '');
        console.log(
          '[CleanFrame:background] name=',
          nameParam,
          'bareUUID=',
          bareUuid
        );
      } catch (e) {
        console.warn('[CleanFrame:background] failed to parse redirect request URL', e);
        return;
      }

      prunePendingCaptures();

      let matchedEntry = null;
      let matchedRequestId = null;

      // Prefer cardUuid correlation
      for (const [reqId, entry] of pendingCaptures.entries()) {
        if (entry.cardUuid && entry.cardUuid === bareUuid) {
          matchedEntry = entry;
          matchedRequestId = reqId;
          console.log('[CleanFrame:background] UUID match found — requestId =', reqId);
          break;
        }
      }

      // Fallback to tabId if UUID correlation fails (newest armed wins)
      if (!matchedEntry) {
        let matchedTs = 0;
        for (const [reqId, entry] of pendingCaptures.entries()) {
          if (entry.tabId === details.tabId && entry.armedAt > matchedTs) {
            matchedEntry = entry;
            matchedRequestId = reqId;
            matchedTs = entry.armedAt;
          }
        }
        if (matchedEntry) {
          console.log('[CleanFrame:background] correlation fallback to tabId used');
        }
      }

      if (!matchedEntry || !matchedRequestId) {
        console.warn(
          '[CleanFrame:background] phantom redirect with no pending capture',
          { bareUuid, tabId: details.tabId }
        );
        return;
      }

      pendingCaptures.delete(matchedRequestId);

      let expiresAt;
      try {
        const loc = new URL(redirectUrl);
        const expires = loc.searchParams.get('Expires');
        expiresAt = expires != null ? Number(expires) * 1000 : undefined;
      } catch {
        expiresAt = undefined;
      }

      console.log(
        '[CleanFrame:background] Sending URL_SNIFFED to tab',
        matchedEntry.tabId,
        '— requestId =',
        matchedEntry.requestId || matchedRequestId
      );
      chrome.tabs.sendMessage(matchedEntry.tabId, {
        type: MSG.URL_SNIFFED,
        requestId: matchedEntry.requestId || matchedRequestId,
        url: redirectUrl,
        expiresAt,
      }).catch(() => { });
    },
    {
      urls: ['*://labs.google/fx/api/trpc/media.getMediaUrl*'],
      types: ['xmlhttprequest', 'other'],
    }
  );
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (!message?.type) return;

  if (message.type === MSG.PING) {
    sendResponse({ ok: true, version: CFG.version });
    return;
  }

  // Content script notifying SW that a phantom-click is about to fire.
  // We register the pending capture so the onBeforeRedirect listener can
  // correlate the network request back to this specific invocation.
  if (
    message.type === MSG.EXPECT_CAPTURE ||
    message.type === MSG.PHANTOM_CLICK_START
  ) {
    const tabId = sender.tab?.id;
    if (tabId != null && message.requestId) {
      prunePendingCaptures();
      pendingCaptures.set(message.requestId, {
        requestId: message.requestId,
        tabId,
        cardUuid: message.cardUuid ?? null,
        armedAt: Date.now(),
        timeoutMs: Number(message.timeoutMs) > 0
          ? Number(message.timeoutMs)
          : DEFAULT_CAPTURE_TIMEOUT_MS,
      });
      console.log(
        '[CleanFrame:background] phantom-click registered',
        message.requestId,
        'tab',
        tabId,
        'cardUuid',
        message.cardUuid ?? null
      );
    }
    sendResponse({ ok: true });
    return;
  }

  if (message.type === MSG.LOOKUP_MEDIA) {
    const tabId = sender.tab?.id;
    const urls = lookupMedia(tabId, message.hints || []);
    sendResponse({ ok: true, urls });
    return;
  }

  // Perform a HEAD probe from the service worker/offscreen context to avoid
  // page CORS restrictions and CSP issues. Response includes key headers.
  if (message.type === MSG.HEAD_PROBE) {
    (async () => {
      const url = message.url;
      if (!url) {
        sendResponse({ ok: false, error: 'url required' });
        return;
      }
      try {
        // Try HEAD first with a short timeout
        let headRes = null;
        try {
          const ctrl = new AbortController();
          const timer = setTimeout(() => ctrl.abort(), 2500);
          headRes = await fetch(url, { method: 'HEAD', mode: 'cors', credentials: 'omit', signal: ctrl.signal });
          clearTimeout(timer);
        } catch (e) {
          headRes = null;
        }

        const headCl = headRes?.headers?.get?.('content-length');
        const headCt = headRes?.headers?.get?.('content-type');

        // If HEAD succeeded and returned a usable content-length, return it
        if (headRes && headRes.ok && headCl && Number(headCl) > 0) {
          sendResponse({
            ok: true,
            status: headRes.status,
            responseOk: true,
            headers: { 'content-length': headCl, 'content-type': headCt },
            fallbackUsed: false,
          });
          return;
        }

        // HEAD failed or didn't provide content-length -> try Range GET fallback
        try {
          const ctrl2 = new AbortController();
          const timer2 = setTimeout(() => ctrl2.abort(), 5000);
          const rangeRes = await fetch(url, {
            method: 'GET',
            mode: 'cors',
            credentials: 'omit',
            headers: { Range: 'bytes=0-255' },
            signal: ctrl2.signal,
          });
          clearTimeout(timer2);

          const status = rangeRes.status;
          const ct = rangeRes.headers.get('content-type');
          const cr = rangeRes.headers.get('content-range');
          let totalSize = null;
          if (status === 206 && cr) {
            const parts = cr.split('/');
            if (parts.length === 2) {
              const n = Number(parts[1]);
              if (!Number.isNaN(n)) totalSize = n;
            }
          }

          // Cancel the body stream to avoid downloading more than needed
          try {
            if (rangeRes.body && typeof rangeRes.body.cancel === 'function') {
              rangeRes.body.cancel();
            }
          } catch (e) {
            // ignore
          }

          const headers = {
            'content-length': totalSize ?? rangeRes.headers.get('content-length'),
            'content-type': ct,
            'content-range': cr,
          };

          sendResponse({ ok: true, status, responseOk: status === 206 || rangeRes.ok, headers, fallbackUsed: true });
          return;
        } catch (e) {
          sendResponse({ ok: false, error: String(e?.message || e) });
          return;
        }
      } catch (e) {
        sendResponse({ ok: false, error: String(e?.message || e) });
      }
    })();
    return true;
  }

  if (message.type === MSG.ENSURE_OFFSCREEN) {
    ensureOffscreen()
      .then(() => sendResponse({ ok: true }))
      .catch((e) => sendResponse({ ok: false, error: String(e) }));
    return true;
  }

  if (
    message.type === MSG.PROCESS_PROGRESS ||
    message.type === MSG.PROCESS_DONE ||
    message.type === MSG.PROCESS_ERROR
  ) {
    if (message.via === 'offscreen') {
      relayToTab(message.tabId, {
        type: message.type,
        jobId: message.jobId,
        ratio: message.ratio,
        statusText: message.statusText,
        error: message.error,
      });

      if (
        message.type === MSG.PROCESS_DONE &&
        message.blobUrl &&
        message.filename
      ) {
        chrome.downloads.download({
          url: message.blobUrl,
          filename: message.filename,
          saveAs: true,
        });
      }
      sendResponse({ ok: true });
      return;
    }
  }

  if (message.type === MSG.PROCESS_VIDEO && message.target !== 'offscreen') {
    const tabId = sender.tab?.id;

    // Immediate ack — do NOT hold the message port open for the full pipeline.
    sendResponse({ ok: true, status: 'started', jobId: message.jobId });

    (async () => {
      try {
        if (message.videoUrl && tabId != null) {
          rememberTabMedia(tabId, message.videoUrl, message.sourceMeta?.bytes);
        }

        await ensureOffscreen();

        // Fire-and-forget to offscreen; progress/done/error come back via emit → relayToTab
        chrome.runtime.sendMessage({
          type: MSG.PROCESS_VIDEO,
          target: 'offscreen',
          jobId: message.jobId,
          videoUrl: message.videoUrl,
          pageUrl: message.pageUrl,
          platform: message.platform,
          watermark: message.watermark,
          sourceMeta: message.sourceMeta,
          tabId,
        }).catch((e) => {
          const error = String(e?.message || e);
          // Ignore benign closed-port noise after offscreen already acked
          if (/message channel closed|asynchronous response/i.test(error)) {
            console.warn('[CleanFrame:background] offscreen port closed (job may still run)', error);
            return;
          }
          relayToTab(tabId, {
            type: MSG.PROCESS_ERROR,
            jobId: message.jobId,
            error,
          });
        });
      } catch (e) {
        const error = String(e?.message || e);
        relayToTab(tabId, {
          type: MSG.PROCESS_ERROR,
          jobId: message.jobId,
          error,
        });
      }
    })();

    return; // sync response already sent — do not return true
  }
});

chrome.runtime.onInstalled.addListener(() => {
  console.info(`[CleanFrame:background] v${CFG.version} service worker ready (media sniffer on)`);
});
